{% set version = "1.7.1" %}

package:
  name: flake8-requirements
  version: {{ version }}

source:
  url: https://github.com/Arkq/flake8-requirements/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 867fe37d974d5d90c12a7ded0e0c79b7bff457f5646c72e9ce753550d0e34aae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - flake8 >=2.0
    - setuptools >=10.0.0
    - toml >=0.7.0

test:
  requires:
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - flake8 --version | grep flake8-requirements

about:
  home: https://github.com/Arkq/flake8-requirements
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This module provides a plug-in for flake8, which checks/validates package import requirements.
  dev_url: https://github.com/Arkq/flake8-requirements

extra:
  recipe-maintainers:
    - dopplershift
